services:
  lmsadmin:
    container_name: lms-admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - REACT_APP_BASE_URL=http://localhost:5000

    volumes:
      - .:/app
      - /app/node_modules
